export const CHANGETAB = 'CHANGETAB';


export const GET_LIST_DATA = 'GET_LIST_DATA';
export const LEFT_CLICK= 'LEFT_CLICK';
export const ADD_SELECT_ITEM ='ADD_SELECT_ITEM';
export const MINUS_SELECT_ITEM = 'MINUS_SELECT_ITEM';
export const SHOW_CHOOSE_CONTENT = 'SHOW_CHOOSE_CONTENT';
export const CLEAR_CAR = 'CLEAR_CAR';
export const GET_RESTANURANT_DATA = 'GET_RESTANURANT_DATA';
export const GET_COMMENT_DATA = 'GET_COMMENT_DATA';